export const siteConfig = {
  name: "Sajal Kumar Mishra",
  title: "Sajal Mishra — Senior Software Developer & Full Stack Engineer",
  description:
    "Sajal Kumar Mishra is a Senior Software Developer and Full Stack Engineer based in Bengaluru, India. 4+ years building scalable web products at Veramatic, Rigi, and GoBOLT.",
  url: "https://sajalmishra.in",
  github: "https://github.com/MSAJAL07",
  linkedin: "https://www.linkedin.com/in/sajal-kumar-mishra/",
  twitter: "https://twitter.com/msajaldev",
  twitterHandle: "@msajaldev",
  email: "sajalmishra44@gmail.com",
  location: "Bengaluru, Karnataka, India",
  keywords: [
    "Sajal Mishra",
    "Sajal Kumar Mishra",
    "Sajal",
    "Software Engineer",
    "Full Stack Developer",
    "Full Stack Engineer",
    "Senior Software Developer",
    "React Developer",
    "Node.js Developer",
    "Next.js Developer",
    "TypeScript Developer",
    "JavaScript Developer",
    "Bengaluru",
    "India",
    "Web Developer India",
  ],
};
