export const siteConfig = {
  name: "Sajal Kumar Mishra",
  title: "Sajal Mishra — Senior Software Developer & Backend Engineer",
  description:
    "Sajal Kumar Mishra is a Senior Software Developer based in Bengaluru, India, specialising in scalable APIs, distributed systems, and full-stack engineering. 4+ years building production systems at Veramatic, Rigi, and GoBOLT.",
  url: "https://sajalmishra.in",
  github: "https://github.com/MSAJAL07",
  linkedin: "https://www.linkedin.com/in/sajal-kumar-mishra/",
  twitter: "https://twitter.com/msajaldev",
  twitterHandle: "@msajaldev",
  email: "sajalmishra44@gmail.com",
  location: "Bengaluru, Karnataka, India",
  keywords: [
    "Sajal Mishra",
    "Sajal Kumar Mishra",
    "Sajal",
    "Software Engineer",
    "Backend Engineer",
    "Backend Developer",
    "Full Stack Developer",
    "Senior Software Developer",
    "Node.js Developer",
    "API Developer",
    "Distributed Systems",
    "TypeScript Developer",
    "JavaScript Developer",
    "React Developer",
    "Bengaluru",
    "India",
    "Software Engineer India",
  ],
};
